### ISSUE TITLE
TypeError: merge.all is not a function

### ISSUE THREAD

**Issue by nonoroazoro** [octokit/endpoint.js#17]
I'm using webpack 4.26.1 with rest.js, but after a successful bundling the application encountered this error `TypeError: merge.all is not a function`.

Then I tried the TypeScript compiler, while it works perfect.

I've found the simillar issue(#1129 ), but it doesn't help at all.

Here is the error stack:
```
TypeError: merge.all is not a function
	at defaultOptions (webpack:///./node_modules/@octokit/endpoint/lib/merge.js?:19:19)
	at withDefaults (webpack:///./node_modules/@octokit/endpoint/with-defaults.js?:8:20)
	at eval (webpack:///./node_modules/@octokit/endpoint/index.js?:4:18)
	at Object../node_modules/@octokit/endpoint/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:96:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/request/index.js?:1:18)
	at Object../node_modules/@octokit/request/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:217:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/constructor.js?:3:18)
	at Object../node_modules/@octokit/rest/lib/constructor.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:306:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/factory.js?:3:17)
	at Object../node_modules/@octokit/rest/lib/factory.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:328:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/core.js?:1:17)
	at Object../node_modules/@octokit/rest/lib/core.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:317:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/index.js?:1:17)
	at Object../node_modules/@octokit/rest/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:295:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
```

After debugging into the package `deepmerge`, I got this:

![default](https://user-images.githubusercontent.com/383132/49203023-a2d72500-f3e1-11e8-9434-835e59aa2bf1.png)

Note that the webpack imports the `deepmerge` from "./node_modules/deepmerge/dist/es.js", which is an ES module. But it doesn't extract the `merge` object from the `default` property of the imported ES module.
Thus, calling `merge.all` will raise the error, instead it should be called as `merge.default.all`, but of cause it cannot be an acceptable solution.

**Comment by gr2m** [comment]
I moved the issue to `@octokit/endpoint.js` as it seems to be the origin of the problem

**Comment by gr2m** [comment]
I was able to reproduce the problem, the build files attached to the releases throw the same error: https://github.com/octokit/endpoint.js/releases

It would be good to add a test that runs with the built file

**Comment by nonoroazoro** [comment]
Great job!
