### ISSUE TITLE
Possible issue with is-plain-object

### ISSUE THREAD

**Issue by michaelmerrill** [octokit/endpoint.js#226]
Hello, I'm trying to debug this error I'm consistently running into when using `@actions/github` in a custom action in my repositories. What's odd is that the exact code works fine in one repo, but not in the other. It's the same action, just copied over. There error is below and seems to stem from this package, but it could also be something else happening in the runner. Any help would be awesome!

```
internal/modules/cjs/loader.js:305
22
      throw err;
23
      ^
24

25
Error: Cannot find module '/home/runner/work/graphql/graphql/.github/actions/terraform-run/node_modules/is-plain-object/dist/is-plain-object.js'. Please verify that the package.json has a valid "main" entry
26
    at tryPackage (internal/modules/cjs/loader.js:297:19)
27
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
28
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
29
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
30
    at Module.require (internal/modules/cjs/loader.js:852:19)
31
    at require (internal/modules/cjs/helpers.js:74:18)
32
    at Object.<anonymous> (/home/runner/work/graphql/graphql/.github/actions/terraform-run/node_modules/@octokit/endpoint/dist-node/index.js:5:21)
33
    at Module._compile (internal/modules/cjs/loader.js:959:30)
34
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
35
    at Module.load (internal/modules/cjs/loader.js:815:32) {
36
  code: 'MODULE_NOT_FOUND',
37
  path: '/home/runner/work/graphql/graphql/.github/actions/terraform-run/node_modules/is-plain-object/package.json',
38
  requestPath: 'is-plain-object'
39
}
```

**Comment by gr2m** [comment]
probably same issue as https://github.com/octokit/rest.js/issues/1929?

**Comment by michaelmerrill** [comment]
Thank you @gr2m!
