### ISSUE TITLE
"Update a webhook configuration for an app" is not available from octokit.

### ISSUE THREAD

**Issue by kuroppe1819** [octokit/endpoint.js#368]
Hello, Thanks for develop a useful library. I have always used octokit.js when using GitHub's API with JavaScript.

## What happened?

I recently tried to update webhook settings of the GitHub App when it failed, because the request URL had been rewritten with an optional parameter "url". The GitHub API I used is [here](https://docs.github.com/en/rest/apps/webhooks#update-a-webhook-configuration-for-an-app).

```ts
await octokit.apps.updateWebhookConfigForApp({
    url: "https://example.com",
});
```

```
/node_modules/@octokit/request/dist-node/index.js:86
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]
    at /node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sendRequestWithRetries (/node_modules/@octokit/auth-app/dist-node/index.js:376:12)
    at async Job.doExecute (/node_modules/bottleneck/light.js:405:18) {
  status: 405,
  response: {
    url: 'https://example.com/',
    status: 405,
    headers: {
      'cache-control': 'max-age=604800',
      connection: 'close',
      'content-length': '0',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Wed, 05 Oct 2022 03:15:29 GMT',
      expires: 'Wed, 12 Oct 2022 03:15:29 GMT',
      server: 'EOS (vny/0453)'
    },
    data: ''
  },
  request: {
    method: 'PATCH',
    url: 'https://example.com',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'probot/12.2.8 octokit-core.js/3.6.0 Node.js/16.11.0 (darwin; arm64)',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    body: '',
    request: {
      hook: [Function: bound bound register],
      retryCount: 3,
      retries: 3,
      retryAfter: 16
    }
  }
}
```

The request url is "https://example.com". This problem is caused by overwriting the url with an optional url in `endpoint.merge` using by `Object.assign`.
https://github.com/octokit/endpoint.js/blob/master/src/merge.ts#L14

reproducible test case: https://runkit.com/kuroppe1819/633c4007c4b5ac0008e59295

## Proposal

Update my GitHub App webhook url by using octokit.js. In order to do that wish to solve the problem of not being able to add URL parameters to the request body.

How about an approach that allows the `body_url` parameter to be specified, e.g.

```ts
const merged = endpoint.merge("PATCH /app/hook/config", {
    body_url: "https://example.com"
});
const parsed = endpoint.parse(merged);

console.log(parsed);
// expect
// {
//   method: "PATCH",
//   url: "https://api.github.com/app/hook/config",
//   headers: {
//     accept: "application/vnd.github.v3+json",
//     user-agent: "octokit-endpoint.js/7.0.2 Node.js/14.20.1 (linux; x64)"
//   },
//   body: {
//     url: "https://example.com"
//   }
// }
```

or body object to merge function argument.

```ts
const merged = endpoint.merge("PATCH /app/hook/config", {
  content_type: "json",
  body: {
    url: "https://example.com",
    secret: "XXXX"
  }
});
const parsed = endpoint.parse(merged);

console.log(parsed);
// expect
// {
//   method: "PATCH",
//   url: "https://api.github.com/app/hook/config",
//   headers: {
//     accept: "application/vnd.github.v3+json",
//     user-agent: "octokit-endpoint.js/7.0.2 Node.js/14.20.1 (linux; x64)"
//   },
//   body: {
//     content_type: "json",
//     url: "https://example.com",
//     secret: "XXXX"
//   }
// }
```

if merge method or parse method interface are able to change it, I think more good approach to do proposal. First, I have suggested a safe implementation. If you have a cooler implementation, please advise.

**Comment by kuroppe1819** [comment]
Thank you for teaching me so kindly.
I tried the 'data' parameter to `updateWebhookConfigForApp `, this problem solved :)

**Comment by gr2m** [comment]
Great, thank you for letting us know
